config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  scope module: :web do
    root 'home#index'

    resources :posts, only: %i[show new create destroy] do
      scope module: :posts do
        resources :comments, only: %i[create] do
          scope module: :comments do
            resources :likes, only: %i[create destroy]
          end
        end
        resources :likes, only: %i[create destroy]
      end
    end

    namespace :account do
      resource :newsletters, only: %i[edit update]
    end

    namespace :admin do
      resources :users, only: :index do
        scope module: :users do
          resources :posts, only: %i[index edit update destroy]
          resources :comments, only: %i[index destroy]
        end
      end
      resources :categories, only: %i[index new create edit update destroy]
    end
  end
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :creator, class_name: 'User', inverse_of: :posts
  belongs_to :category
  has_many :comments, class_name: 'PostComment', dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy

  validates :title, :body, presence: true
  validates :body, length: { minimum: 50 }
end

app/models/post/comment.rb
# frozen_string_literal: true

class Post::Comment < ApplicationRecord
  has_ancestry
  belongs_to :user
  belongs_to :post

  validates :content, presence: true
end

app/controllers/web/admin/users/comments_controller.rb
# frozen_string_literal: true

module Web
  class Admin::Users::CommentsController < Web::Admin::Users::ApplicationController
    def index
      @user = resource_user
      @comments = @user.comments
    end

    def destroy
      comment = resource_user.comments.find_by(id: params[:id])
      comment.destroy

      redirect_to admin_user_comments_path(resource_user)
    end
  end
end

app/controllers/web/admin/users/posts_controller.rb
# frozen_string_literal: true

module Web
  class Admin::Users::PostsController < Web::Admin::Users::ApplicationController
    def index
      @user = resource_user
      @posts = @user.posts
    end

    def edit
      @user = resource_user
      @post = @user.posts.find_by(id: params[:id])
    end

    def update
      @user = resource_user
      @post = @user.posts.find_by(id: params[:id])

      if @post.update(post_params)
        flash[:notice] = t('.success')
        redirect_to action: :index
      else
        flash[:alert] = @post.errors.full_messages.join(' ')
        redirect_to edit_admin_user_post_path(@user, @post)
      end
    end

    def destroy
      post = resource_user.posts.find_by(id: params[:id])

      post.destroy
      flash[:notice] = t('.success')
      redirect_to action: :index
    end

    private

    def post_params
      params.require(:post).permit(:title, :body, :category_id)
    end
  end
end

app/controllers/web/posts/application_controller.rb
# frozen_string_literal: true

module Web
  class Posts::ApplicationController < Web::ApplicationController
    before_action :authenticate_user!

    def resource_post
      @resource_post ||= Post.find params[:post_id]
    end
  end
end

app/controllers/web/posts/comments/application_controller.rb
# frozen_string_literal: true

module Web
  module Posts
    class Comments::ApplicationController < Web::Posts::ApplicationController
      def resource_post_comment
        @resource_post_comment ||= PostComment.find params[:comment_id]
      end
    end
  end
end

app/controllers/web/posts/comments/likes_controller.rb
# frozen_string_literal: true

module Web
  module Posts
    module Comments
      class LikesController < Web::Posts::Comments::ApplicationController
        def create
          resource_post_comment.likes.find_or_create_by(like_params)
          redirect_to resource_post
        end

        def destroy
          like = resource_post_comment.likes.find_by(id: params[:id])
          like&.destroy
          redirect_to resource_post
        end

        private

        def like_params
          { user_id: current_user.id }
        end
      end
    end
  end
end

app/controllers/web/posts/comments_controller.rb
# frozen_string_literal: true

module Web
  class Posts::CommentsController < Posts::ApplicationController
    def create
      comment = resource_post.comments.build(comment_params)
      comment.user = current_user
      if comment.save
        redirect_to resource_post, notice: t('.success')
        MailSender.send_new_comment_mail(comment)
      else
        flash[:alert] = comment&.errors&.full_messages&.join
        redirect_to resource_post
      end
    end

    private

    def comment_params
      params.require(:post_comment).permit(:content, :parent_id)
    end
  end
end

app/controllers/web/posts/likes_controller.rb
# frozen_string_literal: true

module Web
  class Posts::LikesController < Posts::ApplicationController
    def create
      resource_post.likes.find_or_create_by(like_params)
      redirect_to resource_post
    end

    def destroy
      like = resource_post.likes.find_by(id: params[:id])
      like&.destroy
      redirect_to resource_post
    end

    private

    def like_params
      { user_id: current_user.id }
    end
  end
end

app/controllers/web/posts_controller.rb
# frozen_string_literal: true

module Web
  class PostsController < ApplicationController
    before_action :authenticate_user!, only: %i[new create destroy]

    def show
      @post = Post.find(params[:id])
      @comment = @post.comments.build
      @comments = @post.comments.includes(:user, :likes).arrange
      @current_user_like_from_post = @post.likes.find_by(user: current_user)
    end

    def new
      @post = Post.new
    end

    def create
      @post = current_user.posts.build(post_params)

      if @post.save
        redirect_to root_path, notice: t('.succes')
      else
        render :new, status: :unprocessable_entity
      end
    end

    def destroy
      @post = Post.find(params[:id])
      if @post.creator_id != current_user.id
        flash[:alert] = t('.failure_permision')
        redirect_to post_path(@post), status: :unprocessable_entity
      elsif @post.destroy
        redirect_to root_path, notice: t('.succes')
      else
        flash[:alert] = t('.failure')
        redirect_to post_path(@post), status: :unprocessable_entity
      end
    end

    private

    def post_params
      params.require(:post).permit(:title, :body, :category_id)
    end
  end
end

app/views/web/posts/comments/_form.html.slim
= simple_form_for(comment, url: url) do |f|
  = f.input :content, error: false
  -if parent_id.present?
    = f.input :parent_id, as: :hidden, input_html: { value: parent_id }
  = f.button :submit, class: 'btn btn-primary mt-4 btn-block'

app/views/web/posts/comments/_list.html.slim
.mb-3.mt-3
  - comments.each do |comment, child_comments|
    .card.mb-2
      .card-body
        .card-text
          = comment.content
      d-flex.card-footer.text-muted.border-bottom
        = render partial: 'web/shared/creation_data', locals: { email: comment.user.email, created_at: comment.created_at }
        = render partial: 'web/posts/comments/likes/links', locals: { post: post, comment: comment, like: comment.likes.find { |like| like.user_id == current_user&.id } }

        -if child_comments
          = render partial: 'web/posts/comments/list', locals: { comments: child_comments, current_comment: current_comment, post: post }
        div
        - if user_signed_in?
          a.btn.btn-warning[data-bs-toggle="collapse" href="#collapse-#{comment.id}" role="button" aria-expanded="false"]
            span.bi.bi-patch-plus
            = t('.reply')
          .collapse[id="collapse-#{comment.id}"]
            .mb-2.m-4
              = render partial: 'web/posts/comments/form', locals: { comment: current_comment, parent_id: comment.id, url: post_comments_path(post, current_comment) }

app/views/web/posts/comments/_show.html.slim
.mb-3.mt-3
  - comments.each do |comment, child_comments|
    .card.mb-2
      .card-body
        .card-text
          = comment.content
      .card-footer.text-muted.border-bottom
        = render partial: 'web/shared/creation_data', locals: { email: comment.user.email, created_at: comment.created_at }

        -if comment.has_children?
          = render partial: 'web/posts/comments/show', locals: { comments: child_comments, current_comment: current_comment, post: post }
        div
        - if user_signed_in?
          a.text-decoration-none[data-bs-toggle="collapse" href="#collapse-#{comment.id}" role="button" aria-expanded="false"] = t('.reply')
          .collapse[id="collapse-#{comment.id}"]
            .mb-2.m-4
              = render partial: 'web/posts/comments/form', locals: { comment: current_comment, parent_id: comment.id, url: post_comments_path(post, current_comment) }