config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  scope module: :web do
    root 'home#index'

    resources :posts, only: %i[show new create destroy] do
      scope module: :posts do
        resources :comments, only: %i[create] do
          scope module: :comments do
            resources :likes, only: %i[create destroy]
          end
        end
        resources :likes, only: %i[create destroy]
      end
    end

    namespace :account do
      resource :newsletters, only: %i[edit update]
    end

    namespace :admin do
      resources :users, only: :index do
        scope module: :users do
          resources :posts, only: %i[index edit update destroy]
          resources :comments, only: %i[index destroy]
        end
      end
      resources :categories, only: %i[index new create edit update destroy]
    end
  end
end

app/views/layouts/shared/_flash.html.slim
- if flash.any?
  .container.my-2
    - flash.each do |type, msg|
        - if type == 'notice'
           .alert.alert-info
              = msg
        - else
            .alert.alert-danger
              = msg

app/views/layouts/shared/_footer.html.slim
footer.bg-dark.text-light.mt-auto
      .container-xl
        .row.py-2
          = link_to t('.footer_title', year: Time.current.year), t('.link'), class: 'nav-link text-white'

app/views/layouts/shared/_nav.html.slim
.container.mb-2.border-bottom.py-2
  nav.navbar.navbar-expand-lg style='background-color: #e3f2fd;'
    .container-fluid
      = link_to root_path, class: 'navbar-brand text-dark'
        i.fa-solid.fa-home
      ul.navbar-nav.me-auto.mb-2.mb-lg-0
      - if user_signed_in?
        li.nav-item.m-2 style='list-style-type: none;'
          = link_to t('.add_post'), new_post_path, class: 'nav-link text-dark'
        .dropdown
          a.btn.btn-secondary.dropdown-toggle[href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false"] = t('.menu')
          ul.dropdown-menu[aria-labelledby="dropdownMenuLink"]
            li
              = link_to current_user.email, '#', class: 'dropdown-item'
            li
              = link_to t('.settings'), edit_account_newsletters_path, class: 'dropdown-item'
            - if current_user.admin?
              li
                = link_to t('.admin_panel'), admin_users_path, class: 'dropdown-item'
            li
              = link_to t('.log_out'), destroy_user_session_path, method: :delete, class: 'dropdown-item'
      - else
        li.nav-item.m-2 style='list-style-type: none;'
          = link_to t('.sign_in'), new_user_session_path, class: 'btn btn-light'
        li.nav-item.m-2  style='list-style-type: none;'
          = link_to t('.sign_up'), new_user_registration_path, class: 'btn btn-light'