config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  scope module: :web do
    root 'home#index'

    resources :posts, only: %i[show new create destroy] do
      scope module: :posts do
        resources :comments, only: %i[create] do
          scope module: :comments do
            resources :likes, only: %i[create destroy]
          end
        end
        resources :likes, only: %i[create destroy]
      end
    end

    namespace :account do
      resource :newsletters, only: %i[edit update]
    end

    namespace :admin do
      resources :users, only: :index do
        scope module: :users do
          resources :posts, only: %i[index edit update destroy]
          resources :comments, only: %i[index destroy]
        end
      end
      resources :categories, only: %i[index new create edit update destroy]
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  extend Enumerize
  # :confirmable, :lockable, :recoverable, :validatable :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :confirmable, :recoverable, :registerable, :lockable,
         :rememberable, :trackable, :validatable, :trackable

  has_many :posts, foreign_key: 'creator_id', inverse_of: :creator, dependent: :destroy
  has_many :comments, class_name: 'PostComment', dependent: :destroy
  has_many :likes, dependent: :destroy

  enumerize :role, in: %i[user admin], default: :user, predicates: true

  validates :email, format: { with: Devise.email_regexp }

  def initialize(attribute = nil)
    default = {
      email_delivery_enabled: true
    }
    attribute_with_default = attribute ? default.merge(attribute) : default
    super(attribute_with_default)
  end

  def can_send_email?
    email_delivery_enabled && !unconfirmed_email
  end
end

app/controllers/web/admin/users/application_controller.rb
# frozen_string_literal: true

module Web
  class Admin::Users::ApplicationController < Web::Admin::ApplicationController
    def resource_user
      @resource_user ||= User.find_by(id: params[:user_id])
    end
  end
end

app/controllers/web/admin/users/comments_controller.rb
# frozen_string_literal: true

module Web
  class Admin::Users::CommentsController < Web::Admin::Users::ApplicationController
    def index
      @user = resource_user
      @comments = @user.comments
    end

    def destroy
      comment = resource_user.comments.find_by(id: params[:id])
      comment.destroy

      redirect_to admin_user_comments_path(resource_user)
    end
  end
end

app/controllers/web/admin/users/posts_controller.rb
# frozen_string_literal: true

module Web
  class Admin::Users::PostsController < Web::Admin::Users::ApplicationController
    def index
      @user = resource_user
      @posts = @user.posts
    end

    def edit
      @user = resource_user
      @post = @user.posts.find_by(id: params[:id])
    end

    def update
      @user = resource_user
      @post = @user.posts.find_by(id: params[:id])

      if @post.update(post_params)
        flash[:notice] = t('.success')
        redirect_to action: :index
      else
        flash[:alert] = @post.errors.full_messages.join(' ')
        redirect_to edit_admin_user_post_path(@user, @post)
      end
    end

    def destroy
      post = resource_user.posts.find_by(id: params[:id])

      post.destroy
      flash[:notice] = t('.success')
      redirect_to action: :index
    end

    private

    def post_params
      params.require(:post).permit(:title, :body, :category_id)
    end
  end
end

app/controllers/web/admin/users_controller.rb
# frozen_string_literal: true

module Web
  module Admin
    class UsersController < Web::Admin::ApplicationController
      def index
        @users = User.all
      end
    end
  end
end

app/views/web/admin/users/index.html.slim
.d-flex
  = render partial: 'web/admin/shared/nav'
  .d-flex.flex-column.w-100.m-1
    h1 = t('.users')

    table.table
      thead
        tr
          th[scope="col"] = t('.id')
          th[scope="col"] = t('.email')
          th[scope="col"] = t('.role')
          th[scope="col"] = t('.unconfirmed_email')
          th[scope="col"] = t('.current_sign_in_at')
          th[scope="col"] = t('.last_sign_in_at')
          th[scope="col"] = t('.current_sign_in_ip')
          th[scope="col"] = t('.last_sign_in_ip')
      tbody
        -@users.each do |user|
          tr
            td = user.id
            td
              .m-1
                = link_to user.email, admin_user_posts_path(user)
              .m-1
                = link_to t('.comments'), admin_user_comments_path(user)
            td = user.role_text
            td = user.unconfirmed_email ? t('.unconfirm') : t('.confirm')
            td = l(user.current_sign_in_at, format: :long)
            td = l(user.last_sign_in_at, format: :long)
            td = user.current_sign_in_ip
            td = user.last_sign_in_ip